export * from './Сomments/Comments'
export * from './Advantages/Advantages'
export * from './CourseInfo/CourseInfo'
export * from './HhCards/HhCards'
export * from './SeoText/SeoText'
export * from './Skills/Skills'
export * from './SortButtons/SortButtons'
export * from './SearchList/SearchList'
